DELETE FROM ecomstore;

INSERT INTO ecomstore(PRODUCT_NAME,IN_STOCK,QUANTITY,COST_PRICE,SELLING_PRICE,RATING) VALUES(
'headphones','Y',5,126.50,246.50,4.5
);

INSERT INTO ecomstore(PRODUCT_NAME,IN_STOCK,COST_PRICE,SELLING_PRICE,RATING) VALUES(
'pendrive','N',200.50,346.50,4.5
);